# PostgreSQL para Kubernetes (separado)
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: altice-ecommerce
type: Opaque
data:
  postgres-password: YWx0aWNlX3Bhc3N3b3Jk  # altice_password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: altice-ecommerce
data:
  POSTGRES_DB: "altice_ecommerce"
  POSTGRES_USER: "altice_user"
---
apiVersion: v1
kind: Namespace
metadata:
  name: altice-ecommerce
  labels:
    app: altice-ecommerce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: altice-ecommerce
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: altice-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: altice-ecommerce
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432